 -- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 01:33:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotelesappdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelesappdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelesappdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hotelesappdb` ;

-- -----------------------------------------------------
-- Table `hotelesappdb`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`clientes` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`clientes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `verificado` TINYINT(1) NOT NULL DEFAULT '0',
  `es_propietario` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`auth` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`auth` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password_hash` TEXT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cliente_id` BIGINT NULL DEFAULT NULL,
  `temp_token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_auth_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_auth_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `hotelesappdb`.`clientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`ubicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`ubicaciones` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`ubicaciones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `coordenadas` POINT NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `departamento` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`hoteles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`hoteles` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`hoteles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` TEXT NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `estrellas` INT NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `propietario_id` BIGINT NULL DEFAULT NULL,
  `ubicacion_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propietario_cliente` (`propietario_id` ASC) VISIBLE,
  INDEX `fk_ubicacion` (`ubicacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_propietario_cliente`
    FOREIGN KEY (`propietario_id`)
    REFERENCES `hotelesappdb`.`clientes` (`id`),
  CONSTRAINT `fk_ubicacion`
    FOREIGN KEY (`ubicacion_id`)
    REFERENCES `hotelesappdb`.`ubicaciones` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`calificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`calificaciones` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`calificaciones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `hotel_id` BIGINT NULL DEFAULT NULL,
  `cliente_id` BIGINT NULL DEFAULT NULL,
  `calificacion` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_calificacion_hotel` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_calificacion_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_calificacion_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `hotelesappdb`.`clientes` (`id`),
  CONSTRAINT `fk_calificacion_hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `hotelesappdb`.`hoteles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`comentarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `hotel_id` BIGINT NULL DEFAULT NULL,
  `cliente_id` BIGINT NULL DEFAULT NULL,
  `comentario` VARCHAR(1000) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_comentario_hotel` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_comentario_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `hotelesappdb`.`clientes` (`id`),
  CONSTRAINT `fk_comentario_hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `hotelesappdb`.`hoteles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`habitaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`habitaciones` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`habitaciones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `hotel_id` BIGINT NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `precio_por_noche` DECIMAL(10,2) NOT NULL,
  `capacidad` INT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hotel` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `hotelesappdb`.`hoteles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`servicios` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`servicios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`hotel_servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`hotel_servicios` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`hotel_servicios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `hotel_id` BIGINT NULL DEFAULT NULL,
  `servicio_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hotel_servicio_hotel` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_hotel_servicio_servicio` (`servicio_id` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_servicio_hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `hotelesappdb`.`hoteles` (`id`),
  CONSTRAINT `fk_hotel_servicio_servicio`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `hotelesappdb`.`servicios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`imagenes_hoteles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`imagenes_hoteles` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`imagenes_hoteles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `hotel_id` BIGINT NULL DEFAULT NULL,
  `url` TEXT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagenes_hotel` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_imagenes_hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `hotelesappdb`.`hoteles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hotelesappdb`.`reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelesappdb`.`reservas` ;

CREATE TABLE IF NOT EXISTS `hotelesappdb`.`reservas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cliente_id` BIGINT NULL DEFAULT NULL,
  `habitacion_id` BIGINT NULL DEFAULT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_habitacion` (`habitacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `hotelesappdb`.`clientes` (`id`),
  CONSTRAINT `fk_habitacion`
    FOREIGN KEY (`habitacion_id`)
    REFERENCES `hotelesappdb`.`habitaciones` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
